def new_function (funky, clunky):
     answer = funky * clunky
     return answer

vaR = new_function(1,2)
print(vaR)
gene_seq = 'ACTGCTAGCTATCGATCTATATCGCTAGCTACGCGTAGCTACTAATATATCGCGCGGATCGTACTAGCAGGAGACTCTCTAGCACTACACGCGCTAGCTAGC'

for i in gene_seq:
    if i == 'A':
        print('We have an A')
    elif i == 'C':
        print('We have a C')
    elif i == 'T':
        print('We have a T')
    elif i == 'G':
        print('We have a G')
    else:
        print('We do not have an A/C/T/G')





from Bio import SeqIO

record = SeqIO.read("E_Coli.fna", "fasta")
print("Genome length:", len(record.seq))
print("Length:", len(record.seq))
print("First 100 bases:", record.seq[:100])
from Bio.Seq import Seq

print("First 1002 bases:", record.seq[:1002])

dna = Seq('AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAAAAATTACAGAGTACACAACATCCATGAAACGCATTAGCACCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTACAGGAAACACAGAAAAAAGCCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAAGGTAACGAGGTAACAACCATGCGAGTGTTGAAGTTCGGCGGTACATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTCTGGAAAGCAATGCCAGGCAGGGGCAGGTGGCCACCGTCCTCTCTGCCCCCGCCAAAATCACCAACCACCTGGTGGCGATGATTGAAAAAACCATTAGCGGCCAGGATGCTTTACCCAATATCAGCGATGCCGAACGTATTTTTGCCGAACTTTTGACGGGACTCGCCGCCGCCCAGCCGGGGTTCCCGCTGGCGCAATTGAAAACTTTCGTCGATCAGGAATTTGCCCAAATAAAACATGTCCTGCATGGCATTAGTTTGTTGGGGCAGTGCCCGGATAGCATCAACGCTGCGCTGATTTGCCGTGGCGAGAAAATGTCGATCGCCATTATGGCCGGCGTATTAGAAGCGCGCGGTCACAACGTTACTGTTATCGATCCGGTCGAAAAACTGCTGGCAGTGGGGCATTACCTCGAATCTACCGTCGATATTGCTGAGTCCACCCGCCGTATTGCGGCAAGCCGCATTCCGGCTGATCACATGGTGCTGATGGCAGGTTTCACCGCCGGTAATGAAAAAGGCGAACTGGTGGTGCTTGGACGCAACGGTTCCGACTACTCTGCTGCGGTGCTGGCTGCCTGTTTACGCGCCGATT')
protein = dna.translate()
print(protein)


